# joy_inputs_config.yaml

axes:
  roll: 3         # Axis index for roll control
  pitch: 2        # Axis index for pitch control
  yaw: 1          # Axis index for yaw control
  throttle: 0     # Axis index for throttle control
  roll_trim: 5    # Axis index for roll trim control
  pitch_trim: 4   # Axis index for pitch trim control

buttons:
  arm: 1          # Button index for arm control
  kill: 2         # Button index for emergency kill control